test-firead-int-id-typed:
	cd ../int-id/integration-typed; docker compose up --build

test-firead-int-id-untyped:
	cd ../int-id/integration-untyped; docker compose up --build

test-firead-string-id-typed:
	cd ../string-id/integration-typed; docker compose up --build

test-firead-string-id-untyped:
	cd ../string-id/integration-untyped; docker compose up --build